#load libraries
library(dplyr)
library(tidyr)
library(readr)
library(feather)
library(openxlsx)
library(stringr)
library(ggplot2)
library(eurostat)
library(sf)
library(wesanderson)

#set up input and output fps, create dirs
input_fp <- 'Results/descriptives/'
output_fp <- 'Results/visualize/'
dir.create(output_fp, showWarnings = F)
output_fp_viz <- paste0(output_fp, 'descriptives/')
dir.create(output_fp_viz, showWarnings = F)

#load config vectors
var_path <- 'Input Data/Config/vars_visualize_descriptives.xlsx'
dependent_vars <- read.xlsx(var_path, sheet = 'dependent_vars')
dvs_to_keep <- paste0(dependent_vars[dependent_vars$filter == 0,]$vars, '_mean')
dependent_vars <- dependent_vars$vars

immigrant_vars <- read.xlsx(var_path, sheet = 'immigrant_vars')
immigrant_vars <- immigrant_vars$vars

immigrant_chars <- read.xlsx(var_path, sheet = 'immigrant_chars')
personal_chars <- read.xlsx(var_path, sheet = 'personal_chars')
region_vars <- read.xlsx(var_path, sheet = 'region_vars')

#bind all the characteristics for which we have breakdowns
#df structure necessary because we need the plot_type columns later on
all_chars <- bind_rows(immigrant_chars, personal_chars, region_vars)

#Generate map of Europe
#NUTS 2 map
map_2d <- eurostat::get_eurostat_geospatial(output_class = 'sf',
                                         resolution = '60',
                                         nuts_level = '2',
                                         year = '2021'
)
#NUTS 1 map
map_1d <- eurostat::get_eurostat_geospatial(output_class = 'sf',
                                            resolution = '60',
                                            nuts_level = '1',
                                            year = '2021'
) %>%
  mutate(NUTS_ID = paste0(NUTS_ID, '0'))
#bind nuts 1 and nuts 2 maps, so we always get some match
map <- bind_rows(map_2d, map_1d)

#years to keep for maps
years_to_keep_regional <- c(2008, 2012, 2016, 2021)

### Simple immigrant characteristic to dv comparisons by country
#set up fp and dir
output_fp_country_comp <- paste0(output_fp_viz, 'country_comp/')
dir.create(output_fp_country_comp, showWarnings = F)
#loop over country
for(immigrant_var in immigrant_vars){
  basic_all_countries <- data.frame()
  for (country in countries_to_analyze) {
    #load basic dataframes generated by 'descriptives.R'
    temp <- read.csv(paste0(input_fp, '/', country, '/', immigrant_var, '/', 'basic.csv'))
    
    #bind all basic dfs together
    basic_all_countries <- bind_rows(basic_all_countries, temp)
  }
  #get rid of NAs
  basic_all_countries <- basic_all_countries[!is.na(basic_all_countries[[immigrant_var]]),]
  
  #loop over dependent variables
  for(dv in dependent_vars){
    #get variable names
    dv_mean <- paste0(dv, '_mean')
    dv_sd <- paste0(dv, '_sd')
    
    #plot
    p <- ggplot(basic_all_countries)+
      geom_point(aes(x = basic_all_countries[['REFYEAR']], y = basic_all_countries[[dv_mean]], color = as.factor(basic_all_countries[[immigrant_var]])))+
      facet_wrap(. ~ basic_all_countries[['COUNTRY']])+
      xlab('YEAR')+
      ylab(dv)+
      ggtitle(paste0(dv, ' by ', immigrant_var, ', country, and year'))+
      labs(colour=immigrant_var)
    #save
    ggsave(paste0(output_fp_country_comp, immigrant_var, '_', dv, '.png'), plot = last_plot())
  }
}

### within country comparisons ###
for(country in countries_to_analyze){
  print(country)
  
  #set up output fp and dir
  output_fp_country <- paste0(output_fp_viz, country, '/')
  dir.create(output_fp_country, showWarnings = F)
  
  #loop over ivs
  for(iv in immigrant_vars){
    output_fp_immigr <- paste0(output_fp_country, iv, '/')
    dir.create(output_fp_immigr, showWarnings = F)
    
    #loop over chars
    for(i in 1:nrow(all_chars)){
      #get variable name and plot type
      cur_var <- all_chars[i,]$vars
      cur_plot_type <- all_chars[i,]$plot_type
      
      #next if 'drop' -- means I didnt find a good way to display visually
      if(cur_plot_type == 'drop') next
      
      #load basic dataframes generated by 'descriptives.R'
      cur_fp <- paste0(input_fp, country, '/', iv, '/', cur_var, '.csv')
      
      #restrict min number of observations
      cur_df <- read.csv(cur_fp) %>%
        filter(n > 50)
      #remove NAs
      cur_df <- cur_df[(!is.na(cur_df[[iv]]) & !is.na(cur_df[[cur_var]])),]
      
      #next if data frame is empty after rows were dropped and NAs removed
      if(nrow(cur_df) == 0){
        print(paste(country, ': ', iv, ', ', cur_var, ' is empty -- skip'))
        next
      }
      
      #pivot to long
      cur_df_long <- cur_df %>%
        select(-dplyr::ends_with('sd'))%>%
        pivot_longer(cols = dplyr::ends_with('mean'), names_to = 'dv_type', values_to = 'dv') %>%
        filter(dv_type %in% dvs_to_keep)
      
      #Point plot
      if(cur_plot_type == 'point'){
        p <- ggplot(cur_df_long)+
          geom_point(aes(x = cur_df_long[['REFYEAR']], y = cur_df_long[['dv']], color = as.factor(cur_df_long[[iv]])), size = 2)+
          facet_grid(cur_df_long[['dv_type']] ~ as.factor(cur_df_long[[cur_var]]), scales = 'free_y')+
          xlab('Year')+
          ylab('Labor Market outcome')+
          ggtitle(paste0(country, ': Labor market outcomes by ', iv, ', ', cur_var, ', and time'))+
          labs(colour=iv)
        ggsave(paste0(output_fp_immigr, cur_var, '.png'), plot = last_plot(), width = 12, height = 16)
      
      #bar graph
      }else if(cur_plot_type == 'bar'){
        p <- ggplot(cur_df_long)+
          geom_bar(aes(x = cur_df_long[['REFYEAR']], y = cur_df_long[['dv']], fill = as.factor(cur_df_long[[iv]])), stat = 'identity', position = 'dodge')+
          facet_grid(cur_df_long[['dv_type']] ~ as.factor(cur_df_long[[cur_var]]), scales = 'free_y')+
          xlab('Year')+
          ylab('Labor Market outcome')+
          ggtitle(paste0(country, ': Labor market outcomes by ', iv, ', ', cur_var, ', and time'))+
          labs(fill=iv)
        ggsave(paste0(output_fp_immigr, cur_var, '.png'), plot = last_plot(), width = 12, height = 16)
      
      #TODO: was meant to display top and bottom n observations, but was unreadable. Appreciate any ideas for better graphics
      }else if(cur_plot_type == 'top_bottom'){
        #TODO: looks super ugly, any better ideas
        # min_df <- cur_df_long %>%
        #   filter(!(dv_type %in% c('is_unemployed_mean', 'regulated_profession_mean'))) %>%
        #   group_by(REFYEAR, dv_type) %>%
        #   slice_max(n = 3, order_by = dv)
        # max_df <- cur_df_long %>%
        #   filter(!(dv_type %in% c('is_unemployed_mean', 'regulated_profession_mean'))) %>%
        #   group_by(REFYEAR, dv_type) %>%
        #   slice_min(n = 3, order_by = dv)
        # comb_df <- bind_rows(min_df, max_df)
        # p <- ggplot(comb_df)+
        #   geom_bar(aes(x = .data[['REFYEAR']], y = .data[['dv']], fill = as.factor(.data[[cur_var]])), stat = 'identity', position = 'dodge')+
        #   facet_grid(.data[['dv_type']] ~ as.factor(.data[[iv]]), scales = 'free_y')+
        #   xlab('Year')+
        #   ylab('Labor Market outcome')+
        #   ggtitle(paste0(country, ': Labor market outcomes by ', iv, ', ', cur_var, ', and time'))+
        #   labs(fill=iv)
        # ggsave(paste0(output_fp_immigr, cur_var, '.png'), plot = last_plot(), width = 12, height = 16)
      
      #map graphs
      }else if(cur_plot_type == 'map'){
        #prepare output fp and dir
        output_fp_region <- paste0(output_fp_immigr, 'region/')
        dir.create(output_fp_region, showWarnings = F)
        
        #set up map
         cur_map <- map %>%
           filter(CNTR_CODE == country)
         
         #merge results df with map
         cur_df_long_map <- cur_df_long %>%
           mutate(nuts = paste0(COUNTRY, as.character(REGION_2D))) %>%
           left_join(cur_map, by = c('nuts' = 'NUTS_ID'))
         
         #loop over dependent variables: displaying all variables at once gets too confusing for maps
         for(cur_dv in unique(cur_df_long_map$dv_type)){
           #keep only current dv
           cur_df_long_map_restricted <- cur_df_long_map %>%
             filter(dv_type == cur_dv, REFYEAR %in% years_to_keep_regional) %>%
             st_as_sf()
           
           #plot
           ggplot(cur_df_long_map_restricted)+
             geom_sf(aes(fill = .data[['dv']]))+
             scale_fill_gradientn(colours = wesanderson::wes_palette("Zissou1", 100, type = "continuous")) +
             facet_grid(.data[['REFYEAR']] ~ as.factor(.data[[iv]]))+
             labs(fill = cur_dv)+
             ggtitle(paste0(country, ':  ', cur_dv, ' by Region and year'))
           
           #save
           ggsave(paste0(output_fp_region, cur_var, '_', cur_dv, '.png'), plot = last_plot(), width = 12, height = 16)
         }
      }else{
        next
      }
    }
  }
}